### ISSUE TITLE
Cant match nested Array with false values.

### ISSUE THREAD

**Issue by juanpasolano** [deitch/searchjs#49]
I'm not sure If I'm missing something or if it is really a bug.
Given data:
```javascript
const data = [
  {
    cars: [
      {
        exists: true,
        model: "bmw"
      },
      {
        exists: false,
        model: "lada"
      }
    ]
  }
]
```
I cant seem to match the item when searching for `exists: false`;
I've tried
```javascript
{ cars: [{ exists: false }] }
{ "cars.exists": false } // works if searching for true
{ terms: [{ "cars.exists": false }] } // works if searching for true
{ terms: [{ cars: [{ exists: false }] }] }
```
Demo: [https://codesandbox.io/s/y3ow17n9p9](https://codesandbox.io/s/y3ow17n9p9)

**Comment by deitch** [comment]
Hi @juanpasolano .

I think there is a bit of misunderstanding here as to how it works.

The `matchArray()` returns the (possibly empty) list of items at the root of the first argument. In your case, the root array is:

```json
[
  {
    cars: [
      {
        exists: true,
        model: "bmw"
      },
      {
        exists: false,
        model: "lada"
      }
    ]
  }
]
```

This contains exactly one element, an object with one key `cars`, and one value an array with two objects in it.

With each of the search terms you gave, it either will match that entire object, or not the entire object (i.e. empty set).

* `{ cars: [{ exists: true }] }`: This means, "return the single object if it has a key named `cars`, and its value is one of `{exists:true}`. This doesn't match, since its value is actually an array with value `[{exists: true, model: "bmw"},{exists: false, model: "lada"}]`, so it fails.
* `{ "cars.exists": false }`: This uses deep matching, and means, "return the object if there is a key named `cars`, and it in turn has a property named `exists` whose value is false, or has a an array which has an object with that value. See [here](https://github.com/deitch/searchjs#deep-searching-arrays), especially the second example. If it matched, still, the _entire_ `cars` entry would match. As I think about it, I do believe that this one should match, not just `true`. 
* `{ terms: [{ "cars.exists": false }] } `: this is just a variant on the second case.
* `{ terms: [{ cars: [{ exists: false }] }] }`: this is just a variant on the first case.

**Comment by juanpasolano** [comment]
PR would also fix my examples:
https://codesandbox.io/s/kxz8x10nx3
